name: vae-ssm
channels:
  - pip
  - defaults
  - conda-forge
  - pytorch
  - pyg
dependencies:
  - python=3.10.0
  - pip
  - pandas
  - numpy
  - scipy
  - pdblp
  - tqdm
  - jupyterlab
  - pyg-lib
  - pygod
  - pytorch
  - torchvision 
  - torchaudio 
  - networkx
  - scikit-learn
  - statsmodels
  - lightgbm
  - seaborn
  - mkl < 2022
  - pip:
    - fredapi
    - FredMD
